# -*- mode: ruby -*-
# vi: set ft=ruby :

boxes = [
  {
    :name => "linuxMint17",
    :os   => "npalm/mint17-amd64-cinnamon",
    :eth1 => "192.168.88.21",
    :mem  => "512",
    :cpu  => "1"
  },
]

Vagrant.configure(2) do |config|

  boxes.each do |opts|
    config.vm.define opts[:name] do |c|
      c.vm.box      = opts[:os]
      c.vm.hostname = opts[:name]

      # set memory for vms
      c.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--memory", opts[:mem]]
        v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]
      end

      # set network ips
      c.vm.network :private_network, ip: opts[:eth1]
    end
  end
end
